Only compile the test suite if TESTSUITE is defined
This avoids the following linker error:

unresolved external symbol _MemoryModuleTestsuite referenced in function _main